/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import dto.ChatRoomDTO;
import model.Message;
import model.User;
import rmi.IRMI;
import utils.Pair;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 * @author Thanh
 */
class MessagesFrm extends JFrame {

    /**
     * Creates new form NewJFrame2
     */
    private final User user;
    private final String IP;
    private final IRMI rmi;
    private final DefaultTableModel tblChatModel;
    private javax.swing.JTable tblChat;

    private MessagesFrm(User user, String IP, IRMI rmi) {
        this.user = user;
        this.IP = IP;
        this.rmi = rmi;
        initComponents();
        this.setTitle("Tin nhắn -" + this.user.getUsername());
        this.tblChatModel = (DefaultTableModel) tblChat.getModel();
        try {
            List<Pair<ChatRoomDTO, Integer>> status = this.rmi.getChatRoomStatusByUser(user);
            fillTblChat(status);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(User user, String IP, IRMI rmi) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MessagesFrm selectUser = new MessagesFrm(user, IP, rmi);
            selectUser.setVisible(true);
        });
    }


    private void deleteUserTable() {
        int rowCount = tblChatModel.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tblChatModel.removeRow(i);
        }
    }

    private void fillTblChat(List<Pair<ChatRoomDTO, Integer>> listStatus) {
        deleteUserTable();
        listStatus.forEach(pair -> {
            ChatRoomDTO key = pair.getKey();
            List<Pair<User, Message>> messages = key.getMessages();
            System.out.println("A"+messages);
            if(!messages.isEmpty()){
                Pair<User, Message> lastMessage = messages.get(messages.size() - 1);
                String lastUser = lastMessage.getKey().getUsername();
                String lastContent = lastMessage.getValue().getContent();
                tblChatModel.addRow(new Object[]{key.getName(), lastUser + ": " + lastContent, pair.getValue() + " online"});
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane jScrollPane2 = new JScrollPane();
        tblChat = new javax.swing.JTable();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton jButton1 = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblChat.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Chat", "Message"
                }
        ));
        jScrollPane2.setViewportView(tblChat);

        jButton1.setText("Tìm");
        jButton1.addActionListener(this::jButton1ActionPerformed);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(95, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGap(33, 33, 33)
                                .addGap(104, 104, 104)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addGap(111, 111, 111))
                        )
        );
        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        SearchFrm.main(user, IP, rmi);
    }
}
